### ISSUE TITLE
How to make this work on Windows?

### ISSUE THREAD

**Issue by peterwilli** [eowise/gradle-packer-plugin#8]
Hi,

We have a problem making this work on Windows. On Mac it works fine. We downloaded ImageMagick for Windows. We run Windows 7.

Thanks!

(Part of) Error:

	* What went wrong:
	Execution failed for task ':packResizeImagesxhdpichooseadventure'.
	> Process 'command 'convert'' finished with non-zero exit value 4
	
	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
	
	BUILD FAILED
	
	Total time: 4.321 secs
	[sts] Build failed
	org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'http://services.gradle.org/distributions/gradle-2.2-all.zip'.
		at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:53)
		at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
		at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
		at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
		at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:71)
		at org.springsource.ide.eclipse.gradle.core.TaskUtil.execute(TaskUtil.java:117)
		at org.springsource.ide.eclipse.gradle.core.launch.GradleProcess$1.doit(GradleProcess.java:92)
		at org.springsource.ide.eclipse.gradle.core.util.GradleRunnable$1.run(GradleRunnable.java:53)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

Gradle (Packer):

	apply plugin: 'packer'
	task pack(type: com.eowise.packer.Packer) {
	  resourcesInputPath 'images'
	  atlasesOutputPath 'android/assets/atlasses'
	  
	  resolutions {
	    add 'xhdpi'
	    add 'hdpi', 0.75
	    add 'mdpi', 0.5   
	    add 'ldpi', 0.375
	  }
	  
	  atlases {
	    add 'chooseadventure'
	    add 'game'
	    add 'selectlevelmenu'
	    add 'mainmenu'
	    add 'splash'
	  }
	}

**Comment by acatinon** [comment]
Can you give the full stacktrace (with gradle --stacktrace) ?

**Comment by av930** [comment]
This program needs convert.exe that is image convert program.
Therefore if you want to run in windows, you have to install convert.exe in window-bash or cygwin
